sudo: required

services:
 - docker

language: bash

env:
  matrix:
  - TARGET="angelnu/etcd:3.1.12"
    SOURCE_amd64=gcr.io/google_containers/etcd-amd64:3.1.12
    SOURCE_arm64=gcr.io/google_containers/etcd-arm64:3.1.12
    SOURCE_arm=gcr.io/google_containers/etcd-arm:3.1.12

script:
- sudo apt-get install "docker-ce=18.03*"
- >
  mkdir -p $HOME/.docker
  echo '{"experimental": "enabled"}'>$HOME/.docker/config.json
  docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- ./build/build_manifest.sh
